version: '3'
services:
    rundeck:
        container_name: rundeck
        build:
          context: rundeck
          args:
            RUNDECK_IMAGE: ${RUNDECK_IMAGE:-rundeck/rundeck:SNAPSHOT}
        links:
          - mysql
        environment:
            RUNDECK_GRAILS_URL: http://localhost:4440
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
            RUNDECK_SERVER_ADDRESS: 0.0.0.0
            RUNDECK_GUI_STARTPAGE: jobs
        ports:
          - 4440:4440
    mysql:
      container_name: mysql
      image: mysql:8
      expose:
        - 3306
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE reduces error messages in console
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: rundeck
        MYSQL_USER: rundeck
        MYSQL_PASSWORD: rundeck
      volumes:
      - sql-datavolume:/var/lib/mysql
      ulimits:
        nofile:
          soft: 20000
          hard: 40000
      command: --max-connections=1000
    client:
      container_name: client
      build:
        context: client
      environment:
        CONFIG_FILE: import.yml
        RUNDECK_URL: http://rundeck:4440
        RUNDECK_API_URL: http://localhost:4440
        RUNDECK_USER: ${RUNDECK_USER:-admin}
        RUNDECK_PASSWORD: ${RUNDECK_PASSWORD:-admin}
      volumes:
        - shared-volume:/rundeck-cli/data/keys/
    node:
      container_name: node1
      build:
        context: node-demo
      ports:
         - "22"
      environment:
        - SSHD_PORT=22
        - KEY_FILE=/configuration/id_rsa
      volumes:
        - shared-volume:/configuration/
    node2:
      container_name: node2
      build:
        context: node-demo
      ports:
         - "22"
      environment:
        - SSHD_PORT=22
        - KEY_FILE=/configuration/id_rsa
      volumes:
        - shared-volume:/configuration/

volumes:
  shared-volume:
  sql-datavolume:
